package VisualizationDesign.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class Threshold_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_ax5v5s_a(editorContext, node);
  }
  private EditorCell createCollection_ax5v5s_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_ax5v5s_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_ax5v5s_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_ax5v5s_b0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_ax5v5s_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_ax5v5s_d0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_ax5v5s_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_ax5v5s_f0(editorContext, node));
    if (renderingCondition_ax5v5s_a6a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_ax5v5s_g0(editorContext, node));
    }
    if (renderingCondition_ax5v5s_a7a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_ax5v5s_h0(editorContext, node));
    }
    if (renderingCondition_ax5v5s_a8a(node, editorContext)) {
      editorCell.addEditorCell(this.createProperty_ax5v5s_i0(editorContext, node));
    }
    if (renderingCondition_ax5v5s_a9a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_ax5v5s_j0(editorContext, node));
    }
    if (renderingCondition_ax5v5s_a01a(node, editorContext)) {
      editorCell.addEditorCell(this.createConstant_ax5v5s_k0(editorContext, node));
    }
    if (renderingCondition_ax5v5s_a11a(node, editorContext)) {
      editorCell.addEditorCell(this.createProperty_ax5v5s_l0(editorContext, node));
    }
    return editorCell;
  }
  private EditorCell createConstant_ax5v5s_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "Threshold(");
    editorCell.setCellId("Constant_ax5v5s_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_ax5v5s_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "min:");
    editorCell.setCellId("Constant_ax5v5s_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_ax5v5s_c0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("min");
    provider.setNoTargetText("<no min>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_min");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_ax5v5s_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ", max:");
    editorCell.setCellId("Constant_ax5v5s_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createProperty_ax5v5s_e0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("max");
    provider.setNoTargetText("<no max>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_max");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  private EditorCell createConstant_ax5v5s_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ")");
    editorCell.setCellId("Constant_ax5v5s_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createConstant_ax5v5s_g0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "which");
    editorCell.setCellId("Constant_ax5v5s_g0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_ax5v5s_a6a(SNode node, EditorContext editorContext) {
    return SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0x29d64dc129c149b2L, 0xb7eabe15992b2c4aL, 0x3591b3be36b47897L, 0x13c642372f071fdeL, "max")) || SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0x29d64dc129c149b2L, 0xb7eabe15992b2c4aL, 0x3591b3be36b47897L, 0x13c642372f071fd2L, "min"));
  }
  private EditorCell createConstant_ax5v5s_h0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "ceiling is");
    editorCell.setCellId("Constant_ax5v5s_h0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_ax5v5s_a7a(SNode node, EditorContext editorContext) {
    return SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0x29d64dc129c149b2L, 0xb7eabe15992b2c4aL, 0x3591b3be36b47897L, 0x13c642372f071fdeL, "max"));
  }
  private EditorCell createProperty_ax5v5s_i0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("ceiling");
    provider.setNoTargetText("<no ceiling>");
    provider.setAllowsEmptyTarget(true);
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_ceiling");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  private static boolean renderingCondition_ax5v5s_a8a(SNode node, EditorContext editorContext) {
    return SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0x29d64dc129c149b2L, 0xb7eabe15992b2c4aL, 0x3591b3be36b47897L, 0x13c642372f071fdeL, "max"));
  }
  private EditorCell createConstant_ax5v5s_j0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "and");
    editorCell.setCellId("Constant_ax5v5s_j0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_ax5v5s_a9a(SNode node, EditorContext editorContext) {
    return SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0x29d64dc129c149b2L, 0xb7eabe15992b2c4aL, 0x3591b3be36b47897L, 0x13c642372f071fd2L, "min")) && SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0x29d64dc129c149b2L, 0xb7eabe15992b2c4aL, 0x3591b3be36b47897L, 0x13c642372f071fdeL, "max"));
  }
  private EditorCell createConstant_ax5v5s_k0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "floor is");
    editorCell.setCellId("Constant_ax5v5s_k0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private static boolean renderingCondition_ax5v5s_a01a(SNode node, EditorContext editorContext) {
    return SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0x29d64dc129c149b2L, 0xb7eabe15992b2c4aL, 0x3591b3be36b47897L, 0x13c642372f071fd2L, "min"));
  }
  private EditorCell createProperty_ax5v5s_l0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("floor");
    provider.setNoTargetText("<no floor>");
    provider.setAllowsEmptyTarget(true);
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_floor");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      EditorManager manager = EditorManager.getInstanceFromContext(editorContext);
      return manager.createNodeRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
  private static boolean renderingCondition_ax5v5s_a11a(SNode node, EditorContext editorContext) {
    return SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0x29d64dc129c149b2L, 0xb7eabe15992b2c4aL, 0x3591b3be36b47897L, 0x13c642372f071fd2L, "min"));
  }
}
