package VisualizationDesign.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 2:
        return new Dashboard_BehaviorDescriptor();
      case 10:
        return new VBox_BehaviorDescriptor();
      case 11:
        return new Visualization_BehaviorDescriptor();
      case 1:
        return new Concern_BehaviorDescriptor();
      case 3:
        return new Data_BehaviorDescriptor();
      case 7:
        return new Numerical_BehaviorDescriptor();
      case 0:
        return new Boolean_BehaviorDescriptor();
      case 9:
        return new Textual_BehaviorDescriptor();
      case 12:
        return new Window_BehaviorDescriptor();
      case 5:
        return new Enumeration_BehaviorDescriptor();
      case 4:
        return new EElement_BehaviorDescriptor();
      case 8:
        return new Reduce_BehaviorDescriptor();
      case 6:
        return new MoveTo_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"VisualizationDesign.structure.Boolean", "VisualizationDesign.structure.Concern", "VisualizationDesign.structure.Dashboard", "VisualizationDesign.structure.Data", "VisualizationDesign.structure.EElement", "VisualizationDesign.structure.Enumeration", "VisualizationDesign.structure.MoveTo", "VisualizationDesign.structure.Numerical", "VisualizationDesign.structure.Reduce", "VisualizationDesign.structure.Textual", "VisualizationDesign.structure.VBox", "VisualizationDesign.structure.Visualization", "VisualizationDesign.structure.Window"};
}
