package VisualizationDesign.behavior;

/*Generated by MPS */


public class Boolean_BehaviorDescriptor extends Param_BehaviorDescriptor {
  public Boolean_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Boolean";
  }
}
