package VisualizationDesign.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Cell_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Cell_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Cell";
  }
}
