package VisualizationDesign.behavior;

/*Generated by MPS */


public class Colorization_BehaviorDescriptor extends WhatQualifier_BehaviorDescriptor {
  public Colorization_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Colorization";
  }
}
