package VisualizationDesign.behavior;

/*Generated by MPS */


public class Column_BehaviorDescriptor extends Container_BehaviorDescriptor {
  public Column_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Column";
  }
}
