package VisualizationDesign.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Container_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Container_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Container";
  }
}
