package VisualizationDesign.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Data_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Data_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Data";
  }
}
