package VisualizationDesign.behavior;

/*Generated by MPS */


public class Discrete_BehaviorDescriptor extends WhatQualifier_BehaviorDescriptor {
  public Discrete_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Discrete";
  }
}
