package VisualizationDesign.behavior;

/*Generated by MPS */


public class Enumeration_BehaviorDescriptor extends Param_BehaviorDescriptor {
  public Enumeration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Enumeration";
  }
}
