package VisualizationDesign.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class HowQualifier_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public HowQualifier_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.HowQualifier";
  }
}
