package VisualizationDesign.behavior;

/*Generated by MPS */


public class Icon_BehaviorDescriptor extends WhatQualifier_BehaviorDescriptor {
  public Icon_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Icon";
  }
}
