package VisualizationDesign.behavior;

/*Generated by MPS */


public class Line_BehaviorDescriptor extends Container_BehaviorDescriptor {
  public Line_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Line";
  }
}
