package VisualizationDesign.behavior;

/*Generated by MPS */


public class Link_BehaviorDescriptor extends WhatQualifier_BehaviorDescriptor {
  public Link_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Link";
  }
}
