package VisualizationDesign.behavior;

/*Generated by MPS */


public class MoveTo_BehaviorDescriptor extends Interaction_BehaviorDescriptor {
  public MoveTo_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.MoveTo";
  }
}
