package VisualizationDesign.behavior;

/*Generated by MPS */


public class Numerical_BehaviorDescriptor extends Param_BehaviorDescriptor {
  public Numerical_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Numerical";
  }
}
