package VisualizationDesign.behavior;

/*Generated by MPS */


public class Property_BehaviorDescriptor extends WhatQualifier_BehaviorDescriptor {
  public Property_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Property";
  }
}
