package VisualizationDesign.behavior;

/*Generated by MPS */


public class Reduce_BehaviorDescriptor extends Interaction_BehaviorDescriptor {
  public Reduce_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Reduce";
  }
}
