package VisualizationDesign.behavior;

/*Generated by MPS */


public class Structural_BehaviorDescriptor extends WhatQualifier_BehaviorDescriptor {
  public Structural_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Structural";
  }
}
