package VisualizationDesign.behavior;

/*Generated by MPS */


public class Textual_BehaviorDescriptor extends Param_BehaviorDescriptor {
  public Textual_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Textual";
  }
}
