package VisualizationDesign.behavior;

/*Generated by MPS */


public class Threshold_BehaviorDescriptor extends WhatQualifier_BehaviorDescriptor {
  public Threshold_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.Threshold";
  }
}
