package VisualizationDesign.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class VBox_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public VBox_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.VBox";
  }
}
