package VisualizationDesign.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class WhatQualifier_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public WhatQualifier_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "VisualizationDesign.structure.WhatQualifier";
  }
}
