package VisualizationDesign.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum VisuConcern {
  proportion("proportion", "proportion"),
  location("location", "location"),
  comparison("comparison", "comparison"),
  part_to_a_whole("part to a whole", "part-to-a-whole"),
  relationship("relationship", "relationship"),
  over_time("over time", "over-time"),
  distribution("distribution", "distribution"),
  hierarchy("hierarchy", "hierarchy");

  private String myName;
  public String getName() {
    return this.myName;
  }
  public String getValueAsString() {
    return this.myValue;
  }
  public static List<VisuConcern> getConstants() {
    List<VisuConcern> list = ListSequence.fromList(new LinkedList<VisuConcern>());
    ListSequence.fromList(list).addElement(VisuConcern.proportion);
    ListSequence.fromList(list).addElement(VisuConcern.location);
    ListSequence.fromList(list).addElement(VisuConcern.comparison);
    ListSequence.fromList(list).addElement(VisuConcern.part_to_a_whole);
    ListSequence.fromList(list).addElement(VisuConcern.relationship);
    ListSequence.fromList(list).addElement(VisuConcern.over_time);
    ListSequence.fromList(list).addElement(VisuConcern.distribution);
    ListSequence.fromList(list).addElement(VisuConcern.hierarchy);
    return list;
  }
  public static VisuConcern getDefault() {
    return null;
  }
  public static VisuConcern parseValue(String value) {
    if (value == null) {
      return VisuConcern.getDefault();
    }
    if (value.equals(VisuConcern.proportion.getValueAsString())) {
      return VisuConcern.proportion;
    }
    if (value.equals(VisuConcern.location.getValueAsString())) {
      return VisuConcern.location;
    }
    if (value.equals(VisuConcern.comparison.getValueAsString())) {
      return VisuConcern.comparison;
    }
    if (value.equals(VisuConcern.part_to_a_whole.getValueAsString())) {
      return VisuConcern.part_to_a_whole;
    }
    if (value.equals(VisuConcern.relationship.getValueAsString())) {
      return VisuConcern.relationship;
    }
    if (value.equals(VisuConcern.over_time.getValueAsString())) {
      return VisuConcern.over_time;
    }
    if (value.equals(VisuConcern.distribution.getValueAsString())) {
      return VisuConcern.distribution;
    }
    if (value.equals(VisuConcern.hierarchy.getValueAsString())) {
      return VisuConcern.hierarchy;
    }
    return VisuConcern.getDefault();
  }
  private String myValue;
  VisuConcern(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }
  public String getValue() {
    return this.myValue;
  }
}
